import { Css } from "@mui/icons-material";
import { CssBaseline, CssVarsProvider } from "@mui/joy";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sherlock's lifes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CssVarsProvider  disableTransitionOnChange>
              <CssBaseline />
        {children}
        </CssVarsProvider>
      </body>
    </html>
  );
}
